FileDialogPreviousDir<|||>1<|||>/home/danush-soosai/
LastSessions<|||>1<|||>Unnamed
LastActiveSession<|||>1<|||>Unnamed
ColWidths_connform.ListSessions<|||>1<|||>163,50,50,50,50,50,37
ColsVisible_connform.ListSessions<|||>1<|||>0,1,4,6
ColPositions_connform.ListSessions<|||>1<|||>0,1,2,3,4,5,6
ColSort_connform.ListSessions<|||>1<|||>0,1
Servers\Unnamed\SessionCreated<|||>1<|||>2026-05-04 19:56:51
Servers\Unnamed\Host<|||>1<|||>127.0.0.1
Servers\Unnamed\WindowsAuth<|||>3<|||>0
Servers\Unnamed\CleartextPluginEnabled<|||>3<|||>0
Servers\Unnamed\User<|||>1<|||>student_user
Servers\Unnamed\Password<|||>1<|||>78697B7B7F777A6C393A3B8
Servers\Unnamed\LoginPrompt<|||>3<|||>0
Servers\Unnamed\Port<|||>1<|||>3306
Servers\Unnamed\NetType<|||>3<|||>0
Servers\Unnamed\Compressed<|||>3<|||>0
Servers\Unnamed\LocalTimeZone<|||>3<|||>0
Servers\Unnamed\QueryTimeout<|||>3<|||>30
Servers\Unnamed\KeepAlive<|||>3<|||>20
Servers\Unnamed\FullTableStatus<|||>3<|||>0
Servers\Unnamed\Databases<|||>1<|||>course_manager
Servers\Unnamed\Library<|||>1<|||>/lib/x86_64-linux-gnu/libmariadb.so.3
Servers\Unnamed\Comment<|||>1<|||>
Servers\Unnamed\StartupScriptFilename<|||>1<|||>
Servers\Unnamed\TreeBackground<|||>3<|||>536870911
Servers\Unnamed\SSHtunnelActive<|||>3<|||>0
Servers\Unnamed\SshExecutable<|||>1<|||>
Servers\Unnamed\SSHtunnelHost<|||>1<|||>
Servers\Unnamed\SSHtunnelHostPort<|||>3<|||>22
Servers\Unnamed\SSHtunnelUser<|||>1<|||>
Servers\Unnamed\SSHtunnelPassword<|||>1<|||>8
Servers\Unnamed\SSHtunnelTimeout<|||>3<|||>4
Servers\Unnamed\SSHtunnelPrivateKey<|||>1<|||>
Servers\Unnamed\SSHtunnelPort<|||>3<|||>3307
Servers\Unnamed\SSL_Active<|||>3<|||>0
Servers\Unnamed\SSL_Key<|||>1<|||>
Servers\Unnamed\SSL_Cert<|||>1<|||>
Servers\Unnamed\SSL_CA<|||>1<|||>
Servers\Unnamed\SSL_Cipher<|||>1<|||>
Servers\Unnamed\SSL_Verification<|||>3<|||>2
Servers\Unnamed\IgnoreDatabasePattern<|||>1<|||>
Servers\Unnamed\LogFileDdl<|||>3<|||>0
Servers\Unnamed\LogFileDml<|||>3<|||>0
Servers\Unnamed\LogFilePath<|||>1<|||>/home/danush-soosai/.config/heidisql/Logs/%session/%db/%y%m%d.sql
Servers\Unnamed\ServerVersionFull<|||>1<|||>11.8.3-MariaDB-1build1 from Ubuntu - -- Please help get to 10k stars at https://github.com/MariaDB/Server
Servers\Unnamed\ConnectCount<|||>3<|||>1
Servers\Unnamed\ServerVersion<|||>3<|||>110803
Servers\Unnamed\LastConnect<|||>1<|||>2026-05-04 19:57:55
